version: '3.9'
services:
  backend:
    networks:
      - backend
    container_name: post-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: opti-backend
    ports:
      - 4000:4000
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    networks:
      - frontend
    container_name: post-frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: opti-frontend
    ports:
      - 8081:80
    restart: on-failure

  postgres:
    networks:
      - backend
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    networks:
      - backend
    container_name: adminer
    image: adminer
    ports:
      - 8082:8080
    
volumes:
  postgres_data:

networks:
  frontend:
  backend:

